---
- name: Install sudo
  apt:
    state: present
    pkg: aptitude
    update_cache: yes

- name: Create groups if they do not exist
  group:
    name: "{{ item.name }}"
    state: present
  with_items:
    - "{{ sudoers_groups }}"

- name: Ensure groups have proper sudo permissions
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: "^%{{ item.name }}"
    line: "%{{ item.name }} {{ item.perms }}"
    validate: "visudo -cf %s"
  with_items:
    - "{{ sudoers_groups }}"

- name: Create users
  user:
    name: "{{ item.username }}"
    append: "{{ true if item.groups is defined else omit }}"
    groups: "{{ item.groups | default(omit) }}"
    password: "{{ (lookup('password', '/tmp/user_password length=15') | password_hash('sha512'))
      if (item.set_password is defined) else omit }}"
    uid: "{{ item.uid | default(omit) }}"
    shell: "{{ item.shell }}"
    home: "{{ item.home }}"
    update_password: on_create
  notify: Expire user password
  with_items:
    - "{{ users }}"


- name: Add authorized keys for user
  authorized_key:
    user: "{{ item[0].username }}"
    key: "{{ lookup('file', item[1] ) }}"
  with_subelements:
    - "{{ users }}"
    - authorized_keys
